[package]
name = "bs3"
version = "1.0.0"
edition = "2021"

[[bin]]
name = "bs3"
path = "src/main.rs"

[dependencies]
actix-web = "4"
actix-files = "0.6.0"
env_logger = "0.9"
futures-util = { version = "0.3.7" }
log = "0.4"
pin-project = "1"
bytes = "1.1.0"
