[package]
name = "middleware-example"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4"
env_logger = "0.9"
futures-util = { version = "0.3.7", default-features = false, features = ["std"] }
log = "0.4"
pin-project = "1"
bytes = "1.1.0"
